name: default
channels:
  - conda-forge
dependencies:
  - python=3.11.0
  - pip
  - numpy 
  - sympy
  - pandas 
  - scikit-learn 
  - matplotlib 
  - bokeh 
  - plotly=5.11.0
  - seaborn
  - pyarrow 
  - fastparquet 
  - ipython 
  - ipykernel 
  - openpyxl 
  - requests 
  - ipopt
  - glpk
  - pyomo
  - nbformat
  - kneed
  - pip:
    - xmltodict
    - tqdm
    - black
    - structlog